# -*- coding: utf-8 -*-
"""structure_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkdnsffeU6vUb_OHrzDZ33jcFimWBx6Y
"""

#Cell 1 — 설치 (numpy 안 건드림)
!pip install -q biotite

#Cell 2 — annotation CSV 업로드

from google.colab import files
up = files.upload()   # rad51c_residue_annotation.csv 선택
ANNOT_PATH = list(up.keys())[0]

#Cell 3 — WT 구조 다운로드

import urllib.request
PDB_PATH = "rad51c_wt.pdb"
urllib.request.urlretrieve(
    "https://alphafold.ebi.ac.uk/files/AF-O43502-F1-model_v6.pdb", PDB_PATH)
print("downloaded:", PDB_PATH)

#Cell 4 — feature 추출 (구조 6 + 거리 6)

import numpy as np, pandas as pd
import biotite.structure as struc
import biotite.structure.io.pdb as pdb

# 거리 feature 기준이 되는 annotation의 site 컬럼들
SITE_COLS = ["walker_a", "walker_b", "atp_contact",
             "ssdna_binding", "bcdx2_interface", "cx3_interface"]

# Tien et al. 2013 theoretical max ASA (relative SASA 정규화용)
MAX_ASA = {
    "ALA":129.0,"ARG":274.0,"ASN":195.0,"ASP":193.0,"CYS":167.0,
    "GLU":223.0,"GLN":225.0,"GLY":104.0,"HIS":224.0,"ILE":197.0,
    "LEU":201.0,"LYS":236.0,"MET":224.0,"PHE":240.0,"PRO":159.0,
    "SER":155.0,"THR":172.0,"TRP":285.0,"TYR":263.0,"VAL":174.0,
}

f = pdb.PDBFile.read(PDB_PATH)
arr = f.get_structure(model=1, extra_fields=["b_factor"])   # b_factor = pLDDT
arr = arr[struc.filter_amino_acids(arr)]

ca = arr[arr.atom_name == "CA"]      # residue당 1개
res_ids, res_names, n = ca.res_id, ca.res_name, len(ca.res_id)

# 대표 좌표: CB (Gly는 CA)
rep = ca.coord.copy()
cb = arr[arr.atom_name == "CB"]
cb_map = {rid: c for rid, c in zip(cb.res_id, cb.coord)}
for i, rid in enumerate(res_ids):
    if rid in cb_map: rep[i] = cb_map[rid]

# 1) pLDDT  2) secondary structure  3) relative SASA  4) packing density
plddt = ca.b_factor
sse = struc.annotate_sse(arr)                                  # 'a'/'b'/'c'
ss_helix, ss_sheet, ss_loop = (sse=="a").astype(int), (sse=="b").astype(int), (sse=="c").astype(int)
res_sasa = struc.apply_residue_wise(arr, struc.sasa(arr), np.nansum)
rsasa = np.clip([res_sasa[i]/MAX_ASA.get(res_names[i],200.0) for i in range(n)], 0, 1)
dmat = np.linalg.norm(rep[:,None,:]-rep[None,:,:], axis=-1)
packing = (dmat < 10.0).sum(1) - 1

df = pd.DataFrame({
    "position": res_ids, "aa": res_names, "plddt": np.round(plddt,2),
    "ss_helix": ss_helix, "ss_sheet": ss_sheet, "ss_loop": ss_loop,
    "rsasa": np.round(rsasa,4), "packing_density": packing,
})

# 5) 각 기능 자리까지 최소 거리 (annotation의 site 컬럼에서 자동 산출)
annot = pd.read_csv(ANNOT_PATH)
pos_to_idx = {int(p): i for i, p in enumerate(res_ids)}
for col in SITE_COLS:
    idxs = [pos_to_idx[p] for p in annot.loc[annot[col]==1, "position"].astype(int) if p in pos_to_idx]
    df[f"dist_{col}"] = np.round(dmat[:, idxs].min(1), 3) if idxs else np.nan
    if not idxs: print(f"[warn] {col}: 해당 residue 없음 -> NaN")

print(df.shape)
df.head()

#Cell 5 — 저장 (CSV + torch tensor)

import torch

FEAT_COLS = ["plddt","ss_helix","ss_sheet","ss_loop","rsasa","packing_density"] \
            + [f"dist_{c}" for c in SITE_COLS]                       # 총 12-dim

df.to_csv("rad51c_blockA.csv", index=False)                          # 사람용
torch.save({
    "positions": torch.tensor(df["position"].values),               # [376]
    "features":  torch.tensor(df[FEAT_COLS].values, dtype=torch.float32),  # [376, 12]
    "feat_cols": FEAT_COLS,
}, "rad51c_blockA.pt")                                               # 모델용
print("saved:", df[FEAT_COLS].shape, "->", FEAT_COLS)

#Cell 6 — 변이 위치 lookup (missense·indel 공통)

blob = torch.load("rad51c_blockA.pt")
pos2row = {int(p): i for i, p in enumerate(blob["positions"].tolist())}

def block_a(anchor_pos):
    """변이 앵커 position(1-based) -> Block A 구조 feature 벡터 [12].
       missense: 변이 residue 위치 / in-frame indel: 삽입·결실 시작 위치"""
    return blob["features"][pos2row[anchor_pos]]

print(FEAT_COLS)

from google.colab import files

files.download("rad51c_blockA.csv")   # 사람 확인용 테이블
files.download("rad51c_blockA.pt")    # 모델용 [376, 12] 텐서